<?php

return [
    'roles' => [
        'administrator' => 'Administrator',
        'pastor' => 'Pastor',
        'secretary' => 'Secretary',
        'treasurer' => 'Treasurer',
        'accountant' => 'Accountant',
    ],

    'permission_groups' => [
        'members' => ['label' => 'Members', 'icon' => 'fa-users'],
        'leadership' => ['label' => 'Leadership', 'icon' => 'fa-star'],
        'departments' => ['label' => 'Departments', 'icon' => 'fa-sitemap'],
        'announcements' => ['label' => 'Announcements', 'icon' => 'fa-bullhorn'],
        'services' => ['label' => 'Services', 'icon' => 'fa-calendar'],
        'special_events' => ['label' => 'Special Events', 'icon' => 'fa-gift'],
        'attendance' => ['label' => 'Attendance', 'icon' => 'fa-check-square-o'],
        'bereavements' => ['label' => 'Bereavements', 'icon' => 'fa-heart'],
        'finance' => ['label' => 'Finance', 'icon' => 'fa-money'],
        'assets' => ['label' => 'Assets', 'icon' => 'fa-cubes'],
        'reports' => ['label' => 'Reports', 'icon' => 'fa-file-text'],
        'analytics' => ['label' => 'Analytics', 'icon' => 'fa-line-chart'],
        'member_requests' => ['label' => 'Member Requests', 'icon' => 'fa-envelope'],
        'branches' => ['label' => 'Branches', 'icon' => 'fa-code-fork'],
        'system' => ['label' => 'System', 'icon' => 'fa-cogs'],
    ],

    'permission_actions' => [
        'view' => 'View',
        'create' => 'Create',
        'update' => 'Edit',
        'delete' => 'Delete',
        'manage' => 'Manage',
        'approve' => 'Approve',
        'logs' => 'View Logs',
        'sessions' => 'Manage Sessions',
        'users' => 'Manage Users',
        'roles' => 'Manage Roles',
        'monitor' => 'View Monitor',
        'settings' => 'Manage Settings',
    ],

    'member_menu' => [
        [
            'section' => 'menu.sections.main',
            'label' => 'menu.dashboard',
            'icon' => 'fa-dashboard',
            'route' => 'church.member.dashboard',
        ],
        [
            'section' => 'menu.sections.my_church',
            'label' => 'menu.my_profile',
            'icon' => 'fa-user',
            'route' => 'church.member.profile.edit',
        ],
        [
            'section' => 'menu.sections.my_church',
            'label' => 'menu.announcements',
            'icon' => 'fa-bullhorn',
            'route' => 'church.member.announcements.index',
        ],
        [
            'section' => 'menu.sections.my_church',
            'label' => 'menu.leaders',
            'icon' => 'fa-star',
            'route' => 'church.member.leaders.index',
        ],
        [
            'section' => 'menu.sections.my_church',
            'label' => 'menu.my_requests',
            'icon' => 'fa-envelope',
            'route' => 'church.member.requests.index',
        ],
        [
            'section' => 'menu.sections.my_church',
            'label' => 'menu.services',
            'icon' => 'fa-calendar',
            'route' => 'church.member.services.index',
        ],
    ],

    'personal_account_menu' => [
        [
            'section' => 'menu.sections.my_account',
            'label' => 'menu.my_profile',
            'icon' => 'fa-user',
            'route' => 'church.member.profile.edit',
        ],
        [
            'section' => 'menu.sections.my_account',
            'label' => 'menu.my_requests',
            'icon' => 'fa-envelope',
            'route' => 'church.member.requests.index',
        ],
        [
            'section' => 'menu.sections.my_account',
            'label' => 'menu.announcements',
            'icon' => 'fa-bullhorn',
            'route' => 'church.member.announcements.index',
        ],
        [
            'section' => 'menu.sections.my_account',
            'label' => 'menu.services',
            'icon' => 'fa-calendar',
            'route' => 'church.member.services.index',
        ],
    ],

    'menu' => [
        [
            'section' => 'menu.sections.main',
            'label' => 'menu.dashboard',
            'icon' => 'fa-dashboard',
            'route' => 'church.dashboard',
            'permission' => null,
        ],
        [
            'section' => 'menu.sections.management',
            'label' => 'menu.branches',
            'icon' => 'fa-code-fork',
            'feature' => 'branches',
            'permission' => 'branches.view',
            'active' => 'church.branches.*',
            'children' => [
                ['label' => 'menu.view_branches', 'route' => 'church.branches.index', 'permission' => 'branches.view'],
                ['label' => 'menu.add_branch', 'route' => 'church.branches.create', 'permission' => 'branches.manage'],
            ],
        ],
        [
            'section' => 'menu.sections.management',
            'label' => 'menu.member_requests',
            'icon' => 'fa-envelope-open',
            'route' => 'church.member-requests.index',
            'permission' => 'member_requests.view',
            'active' => 'church.member-requests.*',
        ],
        [
            'section' => 'menu.sections.management',
            'label' => 'menu.members',
            'icon' => 'fa-users',
            'permission' => 'members.view',
            'active' => 'church.members.*',
            'children' => [
                ['label' => 'menu.register_member', 'route' => 'church.members.create', 'permission' => 'members.create'],
                ['label' => 'menu.registration_approvals', 'route' => 'church.member-registrations.index', 'permission' => 'member_registrations.view'],
                ['label' => 'menu.view_members', 'route' => 'church.members.index', 'permission' => 'members.view'],
                ['label' => 'menu.archived_members', 'route' => 'church.members.archived', 'permission' => 'members.view'],
                ['label' => 'menu.view_children', 'route' => 'church.members.children.index', 'permission' => 'members.view'],
            ],
        ],
        [
            'section' => 'menu.sections.management',
            'label' => 'menu.leadership',
            'icon' => 'fa-star',
            'permission' => 'leadership.view',
            'active' => 'church.leadership.*',
            'children' => [
                ['label' => 'menu.view_leaders', 'route' => 'church.leadership.index', 'permission' => 'leadership.view'],
                ['label' => 'menu.assign_leadership', 'route' => 'church.leadership.create', 'permission' => 'leadership.manage'],
            ],
        ],
        [
            'section' => 'menu.sections.management',
            'label' => 'menu.departments',
            'icon' => 'fa-sitemap',
            'permission' => 'departments.view',
            'active' => 'church.departments.*',
            'children' => [
                ['label' => 'menu.view_departments', 'route' => 'church.departments.index', 'permission' => 'departments.view'],
                ['label' => 'menu.add_department', 'route' => 'church.departments.create', 'permission' => 'departments.manage'],
            ],
        ],
        [
            'section' => 'menu.sections.management',
            'label' => 'menu.announcements',
            'icon' => 'fa-bullhorn',
            'permission' => 'announcements.view',
            'active' => 'church.announcements.*',
            'children' => [
                ['label' => 'menu.view_announcements', 'route' => 'church.announcements.index', 'permission' => 'announcements.view'],
                ['label' => 'menu.create_announcement', 'route' => 'church.announcements.create', 'permission' => 'announcements.manage'],
            ],
        ],
        [
            'section' => 'menu.sections.management',
            'label' => 'menu.events_services',
            'icon' => 'fa-calendar',
            'permission' => 'services.view',
            'active' => 'church.services.*|church.special-events.*|church.attendance.*|church.bereavements.*|church.promise-guests.*|church.celebrations.*',
            'children' => [
                ['label' => 'menu.services', 'route' => 'church.services.index', 'permission' => 'services.view'],
                ['label' => 'menu.special_events', 'route' => 'church.special-events.index', 'permission' => 'special_events.view'],
                ['label' => 'menu.celebrations', 'route' => 'church.celebrations.index', 'permission' => 'services.view'],
                ['label' => 'menu.promise_guests', 'route' => 'church.promise-guests.index', 'permission' => 'services.view'],
                ['label' => 'menu.attendance', 'route' => 'church.attendance.index', 'permission' => 'attendance.view'],
                ['label' => 'menu.bereavements', 'route' => 'church.bereavements.index', 'permission' => 'bereavements.view'],
            ],
        ],
        [
            'section' => 'menu.sections.management',
            'label' => 'menu.finance',
            'icon' => 'fa-money',
            'permission' => 'finance.view',
            'active' => 'church.finance.*|church.tithes.*|church.offerings.*|church.pledges.*|church.budget.*|church.assets.*',
            'children' => [
                ['label' => 'menu.dashboard', 'route' => 'church.finance.dashboard', 'permission' => 'finance.view'],
                ['label' => 'menu.approval_dashboard', 'route' => 'church.finance.approvals', 'permission' => 'finance.approve'],
                ['label' => 'menu.tithes', 'route' => 'church.tithes.index', 'permission' => 'finance.view'],
                ['label' => 'menu.offerings', 'route' => 'church.offerings.index', 'permission' => 'finance.view'],
                ['label' => 'menu.pledges', 'route' => 'church.pledges.index', 'permission' => 'finance.view'],
                ['label' => 'menu.budget_expenses', 'route' => 'church.budget.index', 'permission' => 'finance.view'],
                ['label' => 'menu.church_assets', 'route' => 'church.assets.index', 'permission' => 'assets.view'],
            ],
        ],
        [
            'section' => 'menu.sections.reports',
            'label' => 'menu.analytics',
            'icon' => 'fa-line-chart',
            'route' => 'church.analytics.index',
            'permission' => 'analytics.view',
        ],
        [
            'section' => 'menu.sections.reports',
            'label' => 'menu.all_reports',
            'icon' => 'fa-file-text',
            'route' => 'church.reports.index',
            'permission' => 'reports.view',
        ],
        [
            'section' => 'menu.sections.administration',
            'label' => 'menu.system_management',
            'icon' => 'fa-cogs',
            'permission' => 'system.users',
            'active' => 'church.system.*',
            'children' => [
                ['label' => 'menu.system_settings', 'route' => 'church.system.settings.index', 'permission' => 'system.settings'],
                ['label' => 'menu.logs', 'route' => 'church.system.logs.index', 'permission' => 'system.logs'],
                ['label' => 'menu.user_sessions', 'route' => 'church.system.sessions.index', 'permission' => 'system.sessions'],
                ['label' => 'menu.manage_users', 'route' => 'church.system.users.index', 'permission' => 'system.users'],
                ['label' => 'menu.roles_permissions', 'route' => 'church.system.roles.index', 'permission' => 'system.roles'],
                ['label' => 'menu.system_monitor', 'route' => 'church.system.monitor.index', 'permission' => 'system.monitor'],
                ['label' => 'menu.otp_management', 'route' => 'church.system.otps.index', 'permission' => 'system.users'],
                ['label' => 'menu.sms_store', 'route' => 'church.system.sms.index', 'permission' => 'system.settings'],
                ['label' => 'menu.upgrade_plan', 'route' => 'church.system.subscription.index', 'permission' => 'system.settings'],
                ['label' => 'menu.terms_conditions', 'route' => 'church.system.subscription.terms'],
            ],
        ],
    ],
];
