<?php

return [
    'roles' => [
        'administrator' => 'Administrator',
        'pastor' => 'Pastor',
        'secretary' => 'Secretary',
        'treasurer' => 'Treasurer',
        'accountant' => 'Accountant',
    ],

    'permission_groups' => [
        'members' => ['label' => 'Members', 'icon' => 'fa-users'],
        'leadership' => ['label' => 'Leadership', 'icon' => 'fa-star'],
        'departments' => ['label' => 'Departments', 'icon' => 'fa-sitemap'],
        'announcements' => ['label' => 'Announcements', 'icon' => 'fa-bullhorn'],
        'services' => ['label' => 'Services', 'icon' => 'fa-calendar'],
        'special_events' => ['label' => 'Special Events', 'icon' => 'fa-gift'],
        'attendance' => ['label' => 'Attendance', 'icon' => 'fa-check-square-o'],
        'bereavements' => ['label' => 'Bereavements', 'icon' => 'fa-heart'],
        'finance' => ['label' => 'Finance', 'icon' => 'fa-money'],
        'assets' => ['label' => 'Assets', 'icon' => 'fa-cubes'],
        'reports' => ['label' => 'Reports', 'icon' => 'fa-file-text'],
        'analytics' => ['label' => 'Analytics', 'icon' => 'fa-line-chart'],
        'member_requests' => ['label' => 'Member Requests', 'icon' => 'fa-envelope'],
        'branches' => ['label' => 'Branches', 'icon' => 'fa-code-fork'],
        'system' => ['label' => 'System', 'icon' => 'fa-cogs'],
    ],

    'permission_actions' => [
        'view' => 'View',
        'create' => 'Create',
        'update' => 'Edit',
        'delete' => 'Delete',
        'manage' => 'Manage',
        'approve' => 'Approve',
        'logs' => 'View Logs',
        'sessions' => 'Manage Sessions',
        'users' => 'Manage Users',
        'roles' => 'Manage Roles',
        'monitor' => 'View Monitor',
        'settings' => 'Manage Settings',
    ],

    'member_menu' => [
        [
            'section' => 'Main',
            'label' => 'Dashboard',
            'icon' => 'fa-dashboard',
            'route' => 'church.member.dashboard',
        ],
        [
            'section' => 'My Church',
            'label' => 'My Profile',
            'icon' => 'fa-user',
            'route' => 'church.member.profile.edit',
        ],
        [
            'section' => 'My Church',
            'label' => 'Announcements',
            'icon' => 'fa-bullhorn',
            'route' => 'church.member.announcements.index',
        ],
        [
            'section' => 'My Church',
            'label' => 'Leaders',
            'icon' => 'fa-star',
            'route' => 'church.member.leaders.index',
        ],
        [
            'section' => 'My Church',
            'label' => 'My Requests',
            'icon' => 'fa-envelope',
            'route' => 'church.member.requests.index',
        ],
        [
            'section' => 'My Church',
            'label' => 'Services',
            'icon' => 'fa-calendar',
            'route' => 'church.member.services.index',
        ],
    ],

    'personal_account_menu' => [
        [
            'section' => 'My Account',
            'label' => 'My Profile',
            'icon' => 'fa-user',
            'route' => 'church.member.profile.edit',
        ],
        [
            'section' => 'My Account',
            'label' => 'My Requests',
            'icon' => 'fa-envelope',
            'route' => 'church.member.requests.index',
        ],
        [
            'section' => 'My Account',
            'label' => 'Announcements',
            'icon' => 'fa-bullhorn',
            'route' => 'church.member.announcements.index',
        ],
        [
            'section' => 'My Account',
            'label' => 'Services',
            'icon' => 'fa-calendar',
            'route' => 'church.member.services.index',
        ],
    ],

    'menu' => [
        [
            'section' => 'Main',
            'label' => 'Dashboard',
            'icon' => 'fa-dashboard',
            'route' => 'church.dashboard',
            'permission' => null,
        ],
        [
            'section' => 'Management',
            'label' => 'Branches',
            'icon' => 'fa-code-fork',
            'feature' => 'branches',
            'permission' => 'branches.view',
            'active' => 'church.branches.*',
            'children' => [
                ['label' => 'View Branches', 'route' => 'church.branches.index', 'permission' => 'branches.view'],
                ['label' => 'Add Branch', 'route' => 'church.branches.create', 'permission' => 'branches.manage'],
            ],
        ],
        [
            'section' => 'Management',
            'label' => 'Member Requests',
            'icon' => 'fa-envelope-open',
            'route' => 'church.member-requests.index',
            'permission' => 'member_requests.view',
            'active' => 'church.member-requests.*',
        ],
        [
            'section' => 'Management',
            'label' => 'Members',
            'icon' => 'fa-users',
            'permission' => 'members.view',
            'active' => 'church.members.*',
            'children' => [
                ['label' => 'Register Member', 'route' => 'church.members.create', 'permission' => 'members.create'],
                ['label' => 'Registration Approvals', 'route' => 'church.member-registrations.index', 'permission' => 'member_registrations.view'],
                ['label' => 'View Members', 'route' => 'church.members.index', 'permission' => 'members.view'],
                ['label' => 'Archived Members', 'route' => 'church.members.archived', 'permission' => 'members.view'],
                ['label' => 'View Children', 'route' => 'church.members.children.index', 'permission' => 'members.view'],
            ],
        ],
        [
            'section' => 'Management',
            'label' => 'Leadership',
            'icon' => 'fa-star',
            'permission' => 'leadership.view',
            'active' => 'church.leadership.*',
            'children' => [
                ['label' => 'View Leaders', 'route' => 'church.leadership.index', 'permission' => 'leadership.view'],
                ['label' => 'Assign Leadership', 'route' => 'church.leadership.create', 'permission' => 'leadership.manage'],
            ],
        ],
        [
            'section' => 'Management',
            'label' => 'Departments',
            'icon' => 'fa-sitemap',
            'permission' => 'departments.view',
            'active' => 'church.departments.*',
            'children' => [
                ['label' => 'View Departments', 'route' => 'church.departments.index', 'permission' => 'departments.view'],
                ['label' => 'Add Department', 'route' => 'church.departments.create', 'permission' => 'departments.manage'],
            ],
        ],
        [
            'section' => 'Management',
            'label' => 'Announcements',
            'icon' => 'fa-bullhorn',
            'permission' => 'announcements.view',
            'active' => 'church.announcements.*',
            'children' => [
                ['label' => 'View Announcements', 'route' => 'church.announcements.index', 'permission' => 'announcements.view'],
                ['label' => 'Create Announcement', 'route' => 'church.announcements.create', 'permission' => 'announcements.manage'],
            ],
        ],
        [
            'section' => 'Management',
            'label' => 'Events & Services',
            'icon' => 'fa-calendar',
            'permission' => 'services.view',
            'active' => 'church.services.*|church.special-events.*|church.attendance.*|church.bereavements.*|church.promise-guests.*|church.celebrations.*',
            'children' => [
                ['label' => 'Services', 'route' => 'church.services.index', 'permission' => 'services.view'],
                ['label' => 'Special Events', 'route' => 'church.special-events.index', 'permission' => 'special_events.view'],
                ['label' => 'Celebrations', 'route' => 'church.celebrations.index', 'permission' => 'services.view'],
                ['label' => 'Promise / Temp Guests', 'route' => 'church.promise-guests.index', 'permission' => 'services.view'],
                ['label' => 'Attendance', 'route' => 'church.attendance.index', 'permission' => 'attendance.view'],
                ['label' => 'Bereavements', 'route' => 'church.bereavements.index', 'permission' => 'bereavements.view'],
            ],
        ],
        [
            'section' => 'Management',
            'label' => 'Finance',
            'icon' => 'fa-money',
            'permission' => 'finance.view',
            'active' => 'church.finance.*|church.tithes.*|church.offerings.*|church.pledges.*|church.budget.*|church.assets.*',
            'children' => [
                ['label' => 'Dashboard', 'route' => 'church.finance.dashboard', 'permission' => 'finance.view'],
                ['label' => 'Approval Dashboard', 'route' => 'church.finance.approvals', 'permission' => 'finance.approve'],
                ['label' => 'Tithes', 'route' => 'church.tithes.index', 'permission' => 'finance.view'],
                ['label' => 'Offerings', 'route' => 'church.offerings.index', 'permission' => 'finance.view'],
                ['label' => 'Pledges', 'route' => 'church.pledges.index', 'permission' => 'finance.view'],
                ['label' => 'Budget & Expenses', 'route' => 'church.budget.index', 'permission' => 'finance.view'],
                ['label' => 'Church Assets', 'route' => 'church.assets.index', 'permission' => 'assets.view'],
            ],
        ],
        [
            'section' => 'Reports',
            'label' => 'Analytics',
            'icon' => 'fa-line-chart',
            'route' => 'church.analytics.index',
            'permission' => 'analytics.view',
        ],
        [
            'section' => 'Reports',
            'label' => 'All Reports',
            'icon' => 'fa-file-text',
            'route' => 'church.reports.index',
            'permission' => 'reports.view',
        ],
        [
            'section' => 'Administration',
            'label' => 'System Management',
            'icon' => 'fa-cogs',
            'permission' => 'system.users',
            'active' => 'church.system.*',
            'children' => [
                ['label' => 'System Settings', 'route' => 'church.system.settings.index', 'permission' => 'system.settings'],
                ['label' => 'Logs', 'route' => 'church.system.logs.index', 'permission' => 'system.logs'],
                ['label' => 'User Sessions', 'route' => 'church.system.sessions.index', 'permission' => 'system.sessions'],
                ['label' => 'Manage Users', 'route' => 'church.system.users.index', 'permission' => 'system.users'],
                ['label' => 'Roles & Permissions', 'route' => 'church.system.roles.index', 'permission' => 'system.roles'],
                ['label' => 'System Monitor', 'route' => 'church.system.monitor.index', 'permission' => 'system.monitor'],
                ['label' => 'OTP Management', 'route' => 'church.system.otps.index', 'permission' => 'system.users'],
                ['label' => 'SMS Store', 'route' => 'church.system.sms.index', 'permission' => 'system.settings'],
                ['label' => 'Upgrade Plan', 'route' => 'church.system.subscription.index', 'permission' => 'system.settings'],
                ['label' => 'Terms & Conditions', 'route' => 'church.system.subscription.terms'],
            ],
        ],
    ],
];
